#!/usr/bin/env python3
"""Bundle web/ into a single self-contained HTML for Squarespace code injection.

CSS and JS are inlined. Images stay as relative src by default; pass an asset
base URL to rewrite them to wherever the images are uploaded (Squarespace file
storage or GitHub Pages), keeping the embed block small enough for Squarespace.

  python3 tools/bundle_embed.py [https://assets.example.org/primer/]
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
web = HERE / "web"
html = (web / "index.html").read_text()
css = (web / "primer.css").read_text()
js = (web / "primer.js").read_text()

html = html.replace('<link rel="stylesheet" href="primer.css">',
                    f"<style>\n{css}\n</style>")
html = html.replace('<script src="primer.js"></script>',
                    f"<script>\n{js}\n</script>")

if len(sys.argv) > 1:
    base = sys.argv[1].rstrip("/") + "/"
    html = re.sub(r'src="assets/', f'src="{base}', html)

# Squarespace injection: strip the document shell, keep head assets + body.
body = re.search(r"<body>(.*)</body>", html, re.S).group(1)
head_assets = "\n".join(re.findall(r'<link rel="preconnect".*?>|<link href="https://fonts[^>]+>', html))
style = re.search(r"<style>.*?</style>", html, re.S).group(0)
script = re.search(r"<script>.*?</script>", html, re.S).group(0)

embed = f"""<!-- Hawaii Budget Primer FY2026-27 — Squarespace code-injection bundle.
     Generated by report2027/tools/bundle_embed.py; do not edit by hand. -->
{head_assets}
{style}
<div class="primer-root">
{body}
</div>
{script}"""

dest = HERE / "dist" / "primer-embed.html"
dest.parent.mkdir(exist_ok=True)
dest.write_text(embed)
print(f"wrote {dest} ({len(embed):,} bytes)")
