"""Scaffold a static HTML page as a new draft-editor project — STAGE ONE.

    python3 -m docsync.scaffold path/to/page.html --id my-page

Takes any self-contained HTML page and makes it OPENABLE in the draft editor
with zero hand-editing: copies the source untouched to
projects/<id>/original.html, generates a wrapper renderer + minimal
content.md/layout.json, appends a binding to docsync.yml, builds once to
prove it, and stages the editor to docs/<id>/.

What it deliberately does NOT do is make anything editable — no text is wired
to a [[slot]], no visual to graphic()/card(). That wiring (STAGE TWO) needs
judgment about which pieces the report's user should own, and is done per
page with the report-editor skill.

The generated renderer wraps the page's <head> styles and <body> verbatim in
the editor's one hard structural requirement: a single <section class="page">
that every drag/resize/snap calculation uses as its coordinate origin.
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "docsync.yml"

_ID_RE = re.compile(r"^[a-z0-9-]+$")

# Pages the editor runs are staged into Pyodide's virtual filesystem — an
# external reference the browser can't resolve inside the iframe is worth a
# loud warning at scaffold time, not a mystery later.
_EXTERNAL_CHECKS = [
    (re.compile(r'<link[^>]+rel=["\']stylesheet["\'][^>]*>', re.I),
     "external stylesheet <link> — its CSS won't load in the editor preview; "
     "inline it into a <style> block in original.html"),
    (re.compile(r'<script[^>]+src=["\'](?!https?:)[^"\']+["\']', re.I),
     "script with a RELATIVE src — the staged dir won't have it; inline it "
     "or drop it"),
    (re.compile(r'<img[^>]+src=["\'](?!https?:|data:)[^"\']+["\']', re.I),
     "image with a RELATIVE src — copy it under the project's assets and "
     "fix the path, or it will 404 in the editor"),
]


def _slug_default(src: Path) -> str:
    return re.sub(r"[^a-z0-9]+", "-", src.stem.lower()).strip("-")


def _extract_title(src_html: str) -> str:
    m = re.search(r"<title[^>]*>(.*?)</title>", src_html, re.S | re.I)
    if not m:
        m = re.search(r"<h1[^>]*>(.*?)</h1>", src_html, re.S | re.I)
    if not m:
        return "Untitled page"
    return re.sub(r"<[^>]+>|\s+", " ", m.group(1)).strip() or "Untitled page"


def _extract_palette(src_html: str, n: int = 8) -> list[str]:
    """The page's own most-used colours, offered first in the colour picker."""
    hexes = re.findall(r"#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{3})\b", src_html)
    counts = Counter(h.upper() if len(h) == 7 else
                     "#" + "".join(c * 2 for c in h[1:]).upper()
                     for h in hexes)
    top = [c for c, _ in counts.most_common(n)]
    if "#FFFFFF" not in top:
        top = top[: n - 1] + ["#FFFFFF"]
    return top


def _warn_externals(src_html: str) -> list[str]:
    warnings = []
    for pattern, msg in _EXTERNAL_CHECKS:
        hits = pattern.findall(src_html)
        if hits:
            warnings.append(f"{len(hits)}x {msg}\n      e.g. {hits[0][:100]}")
    return warnings


_RENDERER = '''#!/usr/bin/env python3
"""{title} renderer — STAGE ONE: openable, not yet editable.

Generated by `python3 -m docsync.scaffold`. original.html is the untouched
source page; this wraps its <head> styles and <body> verbatim in one
`section.page` (the editor's one hard structural requirement) so it opens in
the draft editor exactly as it looks live, with nothing lost.

Nothing is editable yet: no [[slot]] is wired, no visual goes through
docsync.blocks.graphic()/card(). That is STAGE TWO — pick pieces of
original.html and move them into content.md slots one at a time, the way
projects/rxkids did it. See the report-editor skill for the how-to.
"""
from pathlib import Path
import os
import re
import sys

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from docsync.content import Content              # noqa: E402
from docsync.layout import Layout                # noqa: E402

_LAYOUT = Path(os.environ.get("DOCSYNC_LAYOUT") or (HERE / "layout.json"))
_CONTENT = Path(os.environ.get("DOCSYNC_CONTENT") or (HERE / "content.md"))
_OUT = Path(os.environ.get("DOCSYNC_OUT") or (HERE / "index.html"))

# Keep in step with the `page:` in docsync.yml. Height is a generous default —
# a continuous web page just needs the section tall enough not to clip; trim it
# to the content's real bottom once you can see it in the editor.
L = Layout(_LAYOUT, page=({page_w}, {page_h}))
C = Content(_CONTENT, styles=L)

EDIT = bool(os.environ.get("DOCSYNC_EDIT"))

# Edit mode: neutralise scroll-reveal animations. IntersectionObservers don't
# fire usefully inside the editor iframe, so anything the live page reveals on
# scroll would stay invisible (opacity:0) and uneditable. This generic net
# catches the common class conventions; page-specific JS behaviour (image
# cyclers, carousels) still needs a hand-written override — see
# projects/rxkids/render_report.py.
EDIT_CSS = """
[class*="reveal"], [class*="fade"], [class*="animate"], [data-aos] {{
  opacity: 1 !important; transform: none !important;
  visibility: visible !important;
}}
""" if EDIT else ""

SRC = (HERE / "original.html").read_text()

# All <style> blocks that appear BEFORE <body> go into the wrapper's head;
# the body is kept verbatim (any styles inside it still apply where they are).
_body_m = re.search(r"<body[^>]*>(.*)</body>", SRC, re.S | re.I)
BODY = _body_m.group(1) if _body_m else SRC
_head_src = SRC[:_body_m.start()] if _body_m else ""
STYLE = "\\n".join(re.findall(r"<style[^>]*>(.*?)</style>", _head_src, re.S | re.I))

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{C.text("title")}}</title>
<style>
  body {{{{ margin:0; background:#EDF1EE; }}}}
  .page {{{{ width:{{L.page_w}}in; min-height:{{L.page_h}}in; margin:0 auto;
           background:#fff; position:relative; overflow:hidden; }}}}
  {{STYLE}}
  {{EDIT_CSS}}
</style>
</head>
<body>
<section class="page">
{{BODY}}
</section>
{{L.layer(1)}}{{L.text_boxes(1)}}{{L.tables_html(1)}}
</body>
</html>
"""

_OUT.write_text(html)
print(f"wrote {{_OUT}} ({{len(html):,}} bytes)")
'''

_CONTENT_MD = '''<!--
  {title} — scaffolded by `python3 -m docsync.scaffold` to OPEN in the draft
  editor, not yet made editable. original.html is the untouched source;
  render_report.py wraps its styles/<body> verbatim in one page so nothing is
  lost and nothing crashes. Making pieces of it actually editable
  (graphic()/card() from docsync.blocks, L.attr/L.spacer + [[slot]]s) is the
  next step — see the report-editor skill.
-->

[[title]]
{title}

[[sources]]
[example]: Replace or delete this placeholder source — https://example.com
'''

_LAYOUT_JSON = '''{
  "positions": {},
  "shapes": [],
  "boxes": [],
  "tables": []
}
'''

_YML_BINDING = '''
  # {title} — scaffolded by docsync.scaffold as STAGE ONE: openable in the
  # draft editor, not yet editable. STAGE TWO (wiring slots/graphics) is a
  # per-page job — see the report-editor skill. page height is a generous
  # no-clip default for a scrolling web page; trim once visible.
  - id: {slug}
    content: projects/{slug}/content.md
    build: python3 projects/{slug}/render_report.py
    outputs:
      - projects/{slug}/index.html
    editor:
      dir: docs/{slug}
      render: projects/{slug}/render_report.py
      out: projects/{slug}/index.html
      layout: projects/{slug}/layout.json
      palette: [{palette}]
      page: [{page_w}, {page_h}]
      margins: [0.3, 0.3]
      engine:
        # Files render_report.py reads MUST be listed here or the browser's
        # virtual filesystem won't have them ("draft does not build").
        - projects/{slug}/original.html
'''


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Scaffold a static HTML page as a new draft-editor "
                    "project (STAGE ONE: openable, not yet editable).")
    ap.add_argument("source", type=Path, help="path to the source HTML page")
    ap.add_argument("--id", dest="slug",
                    help="project id (lowercase kebab-case; default: from filename)")
    ap.add_argument("--title", help="page title (default: from <title>/<h1>)")
    ap.add_argument("--width", type=float, default=12.5,
                    help="page width in inches (default 12.5 ≈ 1200px, the "
                         "editor's canvas width)")
    ap.add_argument("--height", type=float, default=160,
                    help="page height in inches — a generous no-clip default; "
                         "trim once you can see the content's bottom")
    ap.add_argument("--no-stage", action="store_true",
                    help="skip the build + docsync.stage verification step")
    args = ap.parse_args()

    src = args.source.resolve()
    if not src.is_file():
        ap.error(f"{src} is not a file")
    slug = args.slug or _slug_default(src)
    if not _ID_RE.match(slug):
        ap.error(f"id '{slug}' must be lowercase kebab-case")

    reg_text = REGISTRY.read_text()
    if re.search(rf"^\s+- id: {re.escape(slug)}\s*$", reg_text, re.M):
        ap.error(f"id '{slug}' already exists in docsync.yml")
    proj = ROOT / "projects" / slug
    if proj.exists():
        ap.error(f"{proj} already exists")

    src_html = src.read_text()
    title = args.title or _extract_title(src_html)
    palette = _extract_palette(src_html)

    for w in _warn_externals(src_html):
        print(f"  WARNING: {w}")

    proj.mkdir(parents=True)
    shutil.copy2(src, proj / "original.html")
    (proj / "content.md").write_text(_CONTENT_MD.format(title=title))
    (proj / "layout.json").write_text(_LAYOUT_JSON)
    (proj / "render_report.py").write_text(_RENDERER.format(
        title=title, page_w=args.width, page_h=args.height))

    REGISTRY.write_text(reg_text.rstrip("\n") + "\n" + _YML_BINDING.format(
        slug=slug, title=title, page_w=args.width, page_h=args.height,
        palette=", ".join(f'"{c}"' for c in palette)))

    print(f"scaffolded projects/{slug}/ + docsync.yml binding '{slug}'")

    if not args.no_stage:
        for cmd in (
            [sys.executable, str(proj / "render_report.py")],
            [sys.executable, "-m", "docsync.stage", "--id", slug],
        ):
            r = subprocess.run(cmd, cwd=ROOT)
            if r.returncode != 0:
                print(f"FAILED: {' '.join(cmd)}", file=sys.stderr)
                return 1

    print(f"""
done — '{slug}' is openable in the draft editor (docs/{slug}/edit.html).

next steps:
  - open it and check nothing is clipped or invisible (scroll-reveal
    animations often need an edit-mode override — see projects/rxkids)
  - STAGE TWO: wire text into [[slot]]s and visuals into
    docsync.blocks.graphic()/card() with the report-editor skill""")
    return 0


if __name__ == "__main__":
    sys.exit(main())
